server:
  port: 8686
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
#只需在网关的模块8686配置即可解决所有子模块的跨域问题，其他子模块不用写重复的跨域配置类
            allowed-origins:
              - "http://localhost:8383" #客户端（买家uri）
              - "http://localhost:8282" #客户端（卖家uri）
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      discovery:
        locator:
          enabled: true

